### PR TITLE
Fix for bug: hicPlotMatrix with --log parameter

### PR DESCRIPTION
**Pull request by joachimwolff**
```
matrix = np.array([[0, 1, 2, 0],[2, 3, 0, 1]])
mask = matrix == 0
```
It was the following:
```
> mask is False
False
```
which caused: 
```
IndexError: in the future, 0-d boolean arrays will be interpreted as a valid boolean index
```

What you probably want to have is:
```
> mask == False
array([[False,  True,  True, False],
       [ True,  True, False,  True]], dtype=bool)

```

//Edit:
FYI: This bug is in the master branch too.

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks!

**Comment by bgruening** [comment]
@joachimwolff @fidelram we might want to release a new version.

**Comment by joachimwolff** [comment]
If no more further bugs are know and @fidelram gives his ok, we should release it.

**Comment by fidelram** [comment]
My internal tests had been positive so I let's make the new release.

**Pull request merged**
