### PR TITLE
Bug fix for the case that the index for cut_start starts with 1 and n…

### PR DESCRIPTION
**Pull request by joachimwolff**
…ot with 0.

Fixing bug found by @mzufferey in issue #118.

### CODE REVIEW

**Comment by bgruening** [comment]
ping @fidelram 
Any idea why this should not work?

**Comment by joachimwolff** [comment]
Added bug fix for `hicPlotMatrix --log` as described in PR #126 for development branch.

**Comment by fidelram** [comment]
This should work. I will merge.

**Comment by fidelram** [comment]
@joachimwolff can you check why is the test failing?

**Comment by joachimwolff** [comment]
Linting fails. In this case the liniting rule is wrong and we should ignore it.
`./hicexplorer/hicPlotMatrix.py:458:40: E712 comparison to False should be 'if cond is False:' or 'if not cond:'`

This is exact the condition I changed, see PR #126. 
https://github.com/joachimwolff/HiCExplorer/blob/master/hicexplorer/hicPlotMatrix.py#L458

**Comment by fidelram** [comment]
I merged. We need to exclude the E712 rule from the linting then.

**Pull request merged**
