### PR TITLE
test images using matplotlib.testing, handle NaNs properly for bigwigs

### PR DESCRIPTION
**Pull request by fidelram**
which are based on the RMS diff between the images and a tolerance value. This method replaces the comparison using svg

### CODE REVIEW

**Comment by joachimwolff** [comment]
Can it handle images which are created by different matplotlib versions and or small differences like a different color shape of a plotted line?

**Comment by fidelram** [comment]
That's my expectation. I hope that this issue will also solve the failing tests in the python2to3 branch.

With the new changes, if an image is different than the expected one a 'diff' image is create containing the part with the difference.

I don't know why the galaxy tests fails. I am now adding some functionality to address a recent issue.

**Comment by joachimwolff** [comment]
I have fixed the galaxy issues in my fork of the hicexplorer. Right now the test cases for Python 2 are running and only the plotting test cases (test_plotTads_plotMatrix.py) Python 3 are failing. They fail because of the different behaviour with strings in Python 3 which causes the issues that e.g. a key in a dictionary is now `b'X'` and a `'X' in dict` is now false because `'X' != b'X'`. 

To get the Python 2 testcases running I had to replace the stored test matrices, they were created with the version of hicBuildMatrix which had the bug concerning wrong maximal element values for bin_interval. I think I will do a PR soon.

**Comment by fidelram** [comment]
@bgruening I am merging this branch although the tests are failing for galaxy. The error says that a test svg file is not found, but I see the file as part of the repository. Maybe you can take a look.

**Pull request merged**
