### PR TITLE
Hic export : added new format

### PR DESCRIPTION
**Pull request by vivekbhr**
HiCExport can output bioconductor's GInteraction format now..

### CODE REVIEW

**Comment by fidelram** [comment]
Can you add the restoreMaskedBins part?

**Comment by vivekbhr** [comment]
done.

**Comment by fidelram** [comment]
Why is called GInteractions? Can you expand the help message to include a description of the format?

**Comment by vivekbhr** [comment]
actually I am planning to write a doc page on how to get hicExplorer output to bioconductor for diffHiC and other tools.

**Comment by LeilyR** [comment]
Hey! Do you know how I could use hicExport to convert a matrix from homer to .h5?

**Comment by vivekbhr** [comment]
@LeilyR I don't know homer format.. would have to look into that

**Comment by fidelram** [comment]
I think that the Dekker format can be used. You can ask @DonStephano, I think he imported homer data into HiCExplorer.

**Comment by LeilyR** [comment]
Yes, it is indeed so close to the Dekker format. As far as I understood It has only one extra column of regions at the beginning. Thanks for the help!

**Comment by DonStephano** [comment]
I only used Homer tools for calling A/B compartments. Would be a good feature to import from Homer (and vice versa)

**Comment by LeilyR** [comment]
Also, I was using hicExport to convert a .h5fiel to a .cool file and the .cool file is not getting parsed by cooltools. The reason is the incompatibility between the two naming systems. The name cant be parsed since it is not the UCSC format, as it is accepted by them. Have you every face that issue before? It could be a drosophila specific issue though

**Pull request merged**
